package com.kk.minecraft_chemistry.Items;


import net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback;
import net.minecraft.text.Text;

public class Tooltip_add {

    public static void Add(){
        ItemTooltipCallback.EVENT.register((itemStack, tooltipContext, tooltipType, list) -> {
            // 元素
            if(itemStack.isOf(Initializer.getHydrogen())){
                list.add(Text.translatable("item.chemistry.hydrogen.tooltip1"));
                list.add(Text.translatable("item.chemistry.hydrogen.tooltip2"));
                list.add(Text.translatable("item.chemistry.hydrogen.tooltip3"));
            }
            if(itemStack.isOf(Initializer.getHydrogen())){
                list.add(Text.translatable("item.chemistry.hydrogen.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getHelium())){
                list.add(Text.translatable("item.chemistry.helium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getLithium())){
                list.add(Text.translatable("item.chemistry.lithium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getBeryllium())){
                list.add(Text.translatable("item.chemistry.beryllium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getBoron())){
                list.add(Text.translatable("item.chemistry.boron.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCarbon())){
                list.add(Text.translatable("item.chemistry.carbon.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getNitrogen())){
                list.add(Text.translatable("item.chemistry.nitrogen.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getOxygen())){
                list.add(Text.translatable("item.chemistry.oxygen.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getFluorine())){
                list.add(Text.translatable("item.chemistry.fluorine.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getNeon())){
                list.add(Text.translatable("item.chemistry.neon.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getSodium())){
                list.add(Text.translatable("item.chemistry.sodium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getMagnesium())){
                list.add(Text.translatable("item.chemistry.magnesium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getAluminum())){
                list.add(Text.translatable("item.chemistry.aluminum.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getSilicon())){
                list.add(Text.translatable("item.chemistry.silicon.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getPhosphorus())){
                list.add(Text.translatable("item.chemistry.phosphorus.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getSulfur())){
                list.add(Text.translatable("item.chemistry.sulfur.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getChlorine())){
                list.add(Text.translatable("item.chemistry.chlorine.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getPotassium())){
                list.add(Text.translatable("item.chemistry.potassium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCalcium())){
                list.add(Text.translatable("item.chemistry.calcium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getTitanium())){
                list.add(Text.translatable("item.chemistry.titanium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getChromium())){
                list.add(Text.translatable("item.chemistry.chromium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getManganese())){
                list.add(Text.translatable("item.chemistry.manganese.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getIron())){
                list.add(Text.translatable("item.chemistry.iron.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCobalt())){
                list.add(Text.translatable("item.chemistry.cobalt.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getNickel())){
                list.add(Text.translatable("item.chemistry.nickel.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCopper())){
                list.add(Text.translatable("item.chemistry.copper.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getZinc())){
                list.add(Text.translatable("item.chemistry.zinc.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getGallium())){
                list.add(Text.translatable("item.chemistry.gallium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getSilver())){
                list.add(Text.translatable("item.chemistry.silver.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getTin())){
                list.add(Text.translatable("item.chemistry.tin.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getIodine())){
                list.add(Text.translatable("item.chemistry.iodine.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getTungsten())){
                list.add(Text.translatable("item.chemistry.tungsten.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getGold())){
                list.add(Text.translatable("item.chemistry.gold.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getMercury())){
                list.add(Text.translatable("item.chemistry.mercury.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getLead())){
                list.add(Text.translatable("item.chemistry.lead.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getRadium())){
                list.add(Text.translatable("item.chemistry.radium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getUranium())){
                list.add(Text.translatable("item.chemistry.uranium.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getPlutonium())){
                list.add(Text.translatable("item.chemistry.plutonium.tooltip1"));
            }

            // 化合物
            if(itemStack.isOf(Initializer.getFe2O3())){
                list.add(Text.translatable("item.chemistry.fe2_o3.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getFe3O4())){
                list.add(Text.translatable("item.chemistry.fe3_o4.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getFeO())){
                list.add(Text.translatable("item.chemistry.fe_o.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getNO())){
                list.add(Text.translatable("item.chemistry.n_o.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getNO2())){
                list.add(Text.translatable("item.chemistry.n_o2.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCO())){
                list.add(Text.translatable("item.chemistry.c_o.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCO2())){
                list.add(Text.translatable("item.chemistry.c_o2.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCuO())){
                list.add(Text.translatable("item.chemistry.cu_o.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getAl2O3())){
                list.add(Text.translatable("item.chemistry.al2_o3.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getH2CO3())){
                list.add(Text.translatable("item.chemistry.h2_c_o3.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCaCO3())){
                list.add(Text.translatable("item.chemistry.ca_c_o3.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCaOH2())){
                list.add(Text.translatable("item.chemistry.ca_oh_2.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCaO())){
                list.add(Text.translatable("item.chemistry.ca_o.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getHCl())){
                list.add(Text.translatable("item.chemistry.h_cl.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getH2SO4())){
                list.add(Text.translatable("item.chemistry.h2_s_o4.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getNa2CO3())){
                list.add(Text.translatable("item.chemistry.na2_c_o3.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getC2H5OH())){
                list.add(Text.translatable("item.chemistry.c2_h5_oh.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCH4())){
                list.add(Text.translatable("item.chemistry.c_h4.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getH2O())){
                list.add(Text.translatable("item.chemistry.h2_o.tooltip1"));
            }

            // 其他
//            if(itemStack.isOf(Initializer.getTKMK_Stack())){
//                list.add(Text.translatable("item.chemistry.tkmk_stack.tooltip1"));
//            }
            if(itemStack.isOf(Initializer.getLB_Stack())){
                list.add(Text.translatable("item.chemistry.lb_stack.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getCarbon_Item())){
                list.add(Text.translatable("item.chemistry.carbon_item.tooltip1"));
            }
            if(itemStack.isOf(Initializer.getNO_Extactor())){
                list.add(Text.translatable("item.chemistry.no_extractor.tooltip1"));
            }

        });
    }
}
